spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/AnimeReleaseTracker
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root


app:
  myanimelist-clientId:
  telegram-bot-token:
  force-initialize-season: spring
  force-initialize-year: 2024
